#ifndef HTTPASYNWORK_GLOBAL_H
#define HTTPASYNWORK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HTTPASYNWORK_LIBRARY)
#define HTTPASYNWORK_EXPORT Q_DECL_EXPORT
#else
#define HTTPASYNWORK_EXPORT Q_DECL_IMPORT
#endif

#endif // HTTPASYNWORK_GLOBAL_H
